name = "CodecLz4"
uuid = "5ba52731-8f18-5e0d-9241-30f10d1ec561"
license = "MIT"
author = "Invenia Technical Computing"
version = "0.4.3"

[deps]
Lz4_jll = "5ced341a-0733-55b8-9ab6-a4889d929147"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
Lz4_jll = "1.9"
TranscodingStreams = "0.9, 0.10"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
